spec:
  inputs:
    stage:
      default: "build"
    scala_version:
      default: "2.13.14"
    additional_libs:
      default: ""
---
include:
  - local: /templates/base.yml
    inputs:
      stage: $[[ inputs.stage ]]
      scala_version: '$[[ inputs.scala_version ]]' 
      additional_libs: $[[ inputs.additional_libs ]]
      job_uid: build

.build:
  extends: .sbt-base-build
  script:
    - sbt assembly
    - mv $(find target/ -name *.jar | head -1) target/app.jar
  artifacts:
    paths:
      - target/app.jar
    expire_in: 1 hr
    public: false

build:
  extends: .build
